language: java
jdk:
- oraclejdk8
- oraclejdk8
- openjdk8
- openjdk9
- openjdk10
- openjdk11

install:
  - wget http://apache.cs.utah.edu/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.zip || travis_terminate 1;
    unzip -qq apache-maven-3.5.4-bin.zip || travis_terminate 1;
    export M2_HOME=$PWD/apache-maven-3.5.4;
    export PATH=$M2_HOME/bin:$PATH;

notifications:
  email:
    recipients:
    - jlee@antwerkz.com
    on_success: change
    on_failure: always

script: mvn test ktlint:check